font:
  bold:
    family: xos4 Terminus
    style: Bold
  bold_italic:
    family: xos4 Terminus
    style: Bold Italic
  italic:
    family: xos4 Terminus
    style: Italic
  normal:
    family: xos4 Terminus
    style: Regular
  size: 12

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: F,   mods: Control,           action: SearchForward    }
  - { key: V,   mods: Control,           action: Paste }

selection:
  save_to_clipboard: true


colors:
  primary:
    background: '#181818'
    foreground: '#d0d0d0'

  cursor:
    text: '#000000'
    cursor: '#ffffff'

  vi_mode_cursor:
    text: '#000000'
    cursor: '#ffffff'

  normal:
    black:   '#181818'
    red:     '#ac4142'
    green:   '#90a959'
    yellow:  '#f4bf75'
    blue:    '#6a9fb5'
    magenta: '#aa759f'
    cyan:    '#75b5aa'
    white:   '#d0d0d0'

  bright:
    black:   '#707070'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#f5f5f5'

  search:
    focused_match:
      foreground: '#181818'
      background: '#ab4642'
    matches:
      foreground: '#181818'
      background: '#f4bf75'
    bar:
      foreground: '#d0d0d0'
      background: '#262626'

  selection:
    text: CellForeground
    background: '#303030'
